# Site settings
title: Turtle2Go
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning doesn’t have to feel boring or forced. Find somethingyou love to make it exciting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Turtle2Go.github.io" # the base hostname & protocol for your site
twitter_username: turtle2go
github_username:  turtle2go

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "IT Cloud Engineer"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""